config/routes.rb
SllBiosql::Application.routes.draw do
  get "add_gis_to_queue" => "gi_queues#add_gis_to_queue"
  match "get_gis_sequences", to: "gi_queues#get_gis_sequences", via: [:get,:post]

  resources :functions
  get "functional_hierarchy" => "functions#functional_hierarchy"

  resources :organism_group_rows

  resources :organism_groups
  get "organism_group_by_name/:name" => "organism_groups#show_by_name"

  resources :taxon_attributes

  resources :protein_gi_taxons
  resources :fetch_gis
  
  resources :sequenced_genomes
  get "wgs_ncbi_taxon_ids" => "sequenced_genomes#all_ncbi_taxon_ids"
  get "gi2ncbi_taxon_id" => "protein_gi_taxons#gi2ncbi_taxon_id"
  get "gis2ncbi_taxon_ids" => "protein_gi_taxons#gis2ncbi_taxon_ids"
  resources :taxon_with_names

  root to: "static_pages#home"
  
  get "ncbi_taxon_id2full_taxon_hierarchy" => "taxon_with_names#ncbi_taxon_id2full_taxon_hierarchy"
  get "ncbi_taxon_ids2full_taxon_hierarchies" => "taxon_with_names#ncbi_taxon_ids2full_taxon_hierarchies"
  get "organism_group_name2full_taxon_hierarchies/:name" => "taxon_with_names#organism_group_name2full_taxon_hierarchies"

  get "gis2taxa" => "taxon_with_names#gis2taxa"

end

app/models/organism_group_row.rb
# == Schema Information
#
# Table name: organism_group_rows
#
#  id                :integer         not null, primary key
#  organism_group_id :integer
#  ncbi_taxon_id     :integer
#  created_at        :datetime        not null
#  updated_at        :datetime        not null
#  source_id         :text
#

class OrganismGroupRow < ActiveRecord::Base
  attr_accessible :ncbi_taxon_id, :organism_group_id, :source_id
  belongs_to :organism_group
end

app/controllers/organism_group_rows_controller.rb
class OrganismGroupRowsController < ApplicationController
  # GET /organism_group_rows
  # GET /organism_group_rows.json
  def index
    @organism_group_rows = OrganismGroupRow.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @organism_group_rows }
    end
  end

  # GET /organism_group_rows/1
  # GET /organism_group_rows/1.json
  def show
    @organism_group_row = OrganismGroupRow.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @organism_group_row }
    end
  end

  # GET /organism_group_rows/new
  # GET /organism_group_rows/new.json
  def new
    @organism_group_row = OrganismGroupRow.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @organism_group_row }
    end
  end

  # GET /organism_group_rows/1/edit
  def edit
    @organism_group_row = OrganismGroupRow.find(params[:id])
  end

  # POST /organism_group_rows
  # POST /organism_group_rows.json
  def create
    @organism_group_row = OrganismGroupRow.new(params[:organism_group_row])

    respond_to do |format|
      if @organism_group_row.save
        format.html { redirect_to @organism_group_row, notice: 'Organism group row was successfully created.' }
        format.json { render json: @organism_group_row, status: :created, location: @organism_group_row }
      else
        format.html { render action: "new" }
        format.json { render json: @organism_group_row.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /organism_group_rows/1
  # PUT /organism_group_rows/1.json
  def update
    @organism_group_row = OrganismGroupRow.find(params[:id])

    respond_to do |format|
      if @organism_group_row.update_attributes(params[:organism_group_row])
        format.html { redirect_to @organism_group_row, notice: 'Organism group row was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @organism_group_row.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organism_group_rows/1
  # DELETE /organism_group_rows/1.json
  def destroy
    @organism_group_row = OrganismGroupRow.find(params[:id])
    @organism_group_row.destroy

    respond_to do |format|
      format.html { redirect_to organism_group_rows_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/organism_group_rows_helper.rb
module OrganismGroupRowsHelper
end

app/views/organism_group_rows/_form.html.erb
<%= form_for(@organism_group_row) do |f| %>
  <% if @organism_group_row.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organism_group_row.errors.count, "error") %> prohibited this organism_group_row from being saved:</h2>

      <ul>
      <% @organism_group_row.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :organism_group_id %><br />
    <%= f.number_field :organism_group_id %>
  </div>
  <div class="field">
    <%= f.label :ncbi_taxon_id %><br />
    <%= f.number_field :ncbi_taxon_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/organism_group_rows/edit.html.erb
<h1>Editing organism_group_row</h1>

<%= render 'form' %>

<%= link_to 'Show', @organism_group_row %> |
<%= link_to 'Back', organism_group_rows_path %>

app/views/organism_group_rows/index.html.erb
<h1>Listing organism_group_rows</h1>

<table>
  <tr>
    <th>Organism group</th>
    <th>Ncbi taxon</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @organism_group_rows.each do |organism_group_row| %>
  <tr>
    <td><%= organism_group_row.organism_group_id %></td>
    <td><%= organism_group_row.ncbi_taxon_id %></td>
    <td><%= link_to 'Show', organism_group_row %></td>
    <td><%= link_to 'Edit', edit_organism_group_row_path(organism_group_row) %></td>
    <td><%= link_to 'Destroy', organism_group_row, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Organism group row', new_organism_group_row_path %>

app/views/organism_group_rows/new.html.erb
<h1>New organism_group_row</h1>

<%= render 'form' %>

<%= link_to 'Back', organism_group_rows_path %>

app/views/organism_group_rows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Organism group:</b>
  <%= @organism_group_row.organism_group_id %>
</p>

<p>
  <b>Ncbi taxon:</b>
  <%= @organism_group_row.ncbi_taxon_id %>
</p>


<%= link_to 'Edit', edit_organism_group_row_path(@organism_group_row) %> |
<%= link_to 'Back', organism_group_rows_path %>