config/routes.rb
SllBiosql::Application.routes.draw do
  get "add_gis_to_queue" => "gi_queues#add_gis_to_queue"
  match "get_gis_sequences", to: "gi_queues#get_gis_sequences", via: [:get,:post]

  resources :functions
  get "functional_hierarchy" => "functions#functional_hierarchy"

  resources :organism_group_rows

  resources :organism_groups
  get "organism_group_by_name/:name" => "organism_groups#show_by_name"

  resources :taxon_attributes

  resources :protein_gi_taxons
  resources :fetch_gis
  
  resources :sequenced_genomes
  get "wgs_ncbi_taxon_ids" => "sequenced_genomes#all_ncbi_taxon_ids"
  get "gi2ncbi_taxon_id" => "protein_gi_taxons#gi2ncbi_taxon_id"
  get "gis2ncbi_taxon_ids" => "protein_gi_taxons#gis2ncbi_taxon_ids"
  resources :taxon_with_names

  root to: "static_pages#home"
  
  get "ncbi_taxon_id2full_taxon_hierarchy" => "taxon_with_names#ncbi_taxon_id2full_taxon_hierarchy"
  get "ncbi_taxon_ids2full_taxon_hierarchies" => "taxon_with_names#ncbi_taxon_ids2full_taxon_hierarchies"
  get "organism_group_name2full_taxon_hierarchies/:name" => "taxon_with_names#organism_group_name2full_taxon_hierarchies"

  get "gis2taxa" => "taxon_with_names#gis2taxa"

end

app/models/function.rb
# == Schema Information
#
# Table name: functions
#
#  id                :integer         not null, primary key
#  name              :string(255)
#  source_db         :string(255)
#  source_identifier :string(255)
#  parent_id         :integer
#  created_at        :datetime        not null
#  updated_at        :datetime        not null
#

class Function < ActiveRecord::Base
  attr_accessible :name, :parent_id, :source_db, :source_identifier
  belongs_to :parent, :class_name => "Function", :foreign_key => "parent_id"
  has_many :children, :class_name => "Function", :foreign_key => "parent_id"
  validates :name, presence: true, uniqueness: { scope: :source_db }

  def full_hierarchy
    parent_id ? [ self ] + parent.full_hierarchy : [ self ]
  end

  def hierarchy
    parent_id ? "#{parent.hierarchy}:#{name}" : name
  end

  def root
    parent_id ? parent.root : self
  end
end

app/controllers/functions_controller.rb
class FunctionsController < ApplicationController
  # GET /functions
  # GET /functions.json
  def index
    @functions = Function.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @functions }
    end
  end

  # GET /functions/1
  # GET /functions/1.json
  def show
    @function = Function.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @function }
    end
  end

  # GET /functions/hierarchy/?source_db=SEED&name=Function
  # GET /functions/1.json
  def functional_hierarchy
    qparams = { 
      source_db: params[:source_db],
      name: params[:name]
    }
    @hierarchy = Function.where(qparams).first.full_hierarchy

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @hierarchy }
    end
  end

  # GET /functions/new
  # GET /functions/new.json
  def new
    @function = Function.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @function }
    end
  end

  # GET /functions/1/edit
  def edit
    @function = Function.find(params[:id])
  end

  # POST /functions
  # POST /functions.json
  def create
    @function = Function.new(params[:function])

    respond_to do |format|
      if @function.save
        format.html { redirect_to @function, notice: 'Function was successfully created.' }
        format.json { render json: @function, status: :created, location: @function }
      else
        format.html { render action: "new" }
        format.json { render json: @function.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /functions/1
  # PUT /functions/1.json
  def update
    @function = Function.find(params[:id])

    respond_to do |format|
      if @function.update_attributes(params[:function])
        format.html { redirect_to @function, notice: 'Function was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @function.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /functions/1
  # DELETE /functions/1.json
  def destroy
    @function = Function.find(params[:id])
    @function.destroy

    respond_to do |format|
      format.html { redirect_to functions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/functions_helper.rb
module FunctionsHelper
end

app/views/functions/_form.html.erb
<%= form_for(@function) do |f| %>
  <% if @function.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@function.errors.count, "error") %> prohibited this function from being saved:</h2>

      <ul>
      <% @function.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :source_db %><br />
    <%= f.text_field :source_db %>
  </div>
  <div class="field">
    <%= f.label :source_identifier %><br />
    <%= f.text_field :source_identifier %>
  </div>
  <div class="field">
    <%= f.label :parent_id %><br />
    <%= f.number_field :parent_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/functions/edit.html.erb
<h1>Editing function</h1>

<%= render 'form' %>

<%= link_to 'Show', @function %> |
<%= link_to 'Back', functions_path %>

app/views/functions/index.html.erb
<h1>Listing functions</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Source db</th>
    <th>Source identifier</th>
    <th>Parent</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @functions.each do |function| %>
  <tr>
    <td><%= function.name %></td>
    <td><%= function.source_db %></td>
    <td><%= function.source_identifier %></td>
    <td><%= function.parent_id %></td>
    <td><%= link_to 'Show', function %></td>
    <td><%= link_to 'Edit', edit_function_path(function) %></td>
    <td><%= link_to 'Destroy', function, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Function', new_function_path %>

app/views/functions/new.html.erb
<h1>New function</h1>

<%= render 'form' %>

<%= link_to 'Back', functions_path %>

app/views/functions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @function.name %>
</p>

<p>
  <b>Source db:</b>
  <%= @function.source_db %>
</p>

<p>
  <b>Source identifier:</b>
  <%= @function.source_identifier %>
</p>

<p>
  <b>Parent:</b>
  <%= @function.parent_id %>
</p>


<%= link_to 'Edit', edit_function_path(@function) %> |
<%= link_to 'Back', functions_path %>