config/routes.rb
SllBiosql::Application.routes.draw do
  get "add_gis_to_queue" => "gi_queues#add_gis_to_queue"
  match "get_gis_sequences", to: "gi_queues#get_gis_sequences", via: [:get,:post]

  resources :functions
  get "functional_hierarchy" => "functions#functional_hierarchy"

  resources :organism_group_rows

  resources :organism_groups
  get "organism_group_by_name/:name" => "organism_groups#show_by_name"

  resources :taxon_attributes

  resources :protein_gi_taxons
  resources :fetch_gis
  
  resources :sequenced_genomes
  get "wgs_ncbi_taxon_ids" => "sequenced_genomes#all_ncbi_taxon_ids"
  get "gi2ncbi_taxon_id" => "protein_gi_taxons#gi2ncbi_taxon_id"
  get "gis2ncbi_taxon_ids" => "protein_gi_taxons#gis2ncbi_taxon_ids"
  resources :taxon_with_names

  root to: "static_pages#home"
  
  get "ncbi_taxon_id2full_taxon_hierarchy" => "taxon_with_names#ncbi_taxon_id2full_taxon_hierarchy"
  get "ncbi_taxon_ids2full_taxon_hierarchies" => "taxon_with_names#ncbi_taxon_ids2full_taxon_hierarchies"
  get "organism_group_name2full_taxon_hierarchies/:name" => "taxon_with_names#organism_group_name2full_taxon_hierarchies"

  get "gis2taxa" => "taxon_with_names#gis2taxa"

end

app/models/taxon_attribute.rb
# == Schema Information
#
# Table name: taxon_attributes
#
#  id            :integer         not null, primary key
#  ncbi_taxon_id :integer
#  created_at    :datetime        not null
#  updated_at    :datetime        not null
#  attrs         :string(255)
#

class TaxonAttribute < ActiveRecord::Base
  attr_accessible :ncbi_taxon_id, :attrs
  store :attrs, accessors: [ :ncbi_genome_aa_file_path, :ncbi_genome_nuc_file_path ]
  validates :ncbi_taxon_id, uniqueness: true
end

app/controllers/taxon_attributes_controller.rb
class TaxonAttributesController < ApplicationController
  # GET /taxon_attributes
  # GET /taxon_attributes.json
  def index
    @taxon_attributes = TaxonAttribute.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @taxon_attributes }
    end
  end

  # GET /taxon_attributes/1
  # GET /taxon_attributes/1.json
  def show
    @taxon_attribute = TaxonAttribute.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @taxon_attribute }
    end
  end

  # GET /taxon_attributes/new
  # GET /taxon_attributes/new.json
  def new
    @taxon_attribute = TaxonAttribute.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @taxon_attribute }
    end
  end

  # GET /taxon_attributes/1/edit
  def edit
    @taxon_attribute = TaxonAttribute.find(params[:id])
  end

  # POST /taxon_attributes
  # POST /taxon_attributes.json
  def create
    @taxon_attribute = TaxonAttribute.new(params[:taxon_attribute])

    respond_to do |format|
      if @taxon_attribute.save
        format.html { redirect_to @taxon_attribute, notice: 'Taxon attribute was successfully created.' }
        format.json { render json: @taxon_attribute, status: :created, location: @taxon_attribute }
      else
        format.html { render action: "new" }
        format.json { render json: @taxon_attribute.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /taxon_attributes/1
  # PUT /taxon_attributes/1.json
  def update
    @taxon_attribute = TaxonAttribute.find(params[:id])

    respond_to do |format|
      if @taxon_attribute.update_attributes(params[:taxon_attribute])
        format.html { redirect_to @taxon_attribute, notice: 'Taxon attribute was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @taxon_attribute.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /taxon_attributes/1
  # DELETE /taxon_attributes/1.json
  def destroy
    @taxon_attribute = TaxonAttribute.find(params[:id])
    @taxon_attribute.destroy

    respond_to do |format|
      format.html { redirect_to taxon_attributes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/taxon_attributes_helper.rb
module TaxonAttributesHelper
end

app/views/taxon_attributes/_form.html.erb
<%= form_for(@taxon_attribute) do |f| %>
  <% if @taxon_attribute.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@taxon_attribute.errors.count, "error") %> prohibited this taxon_attribute from being saved:</h2>

      <ul>
      <% @taxon_attribute.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ncbi_taxon_id %><br />
    <%= f.number_field :ncbi_taxon_id %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/taxon_attributes/edit.html.erb
<h1>Editing taxon_attribute</h1>

<%= render 'form' %>

<%= link_to 'Show', @taxon_attribute %> |
<%= link_to 'Back', taxon_attributes_path %>

app/views/taxon_attributes/index.html.erb
<h1>Listing taxon_attributes</h1>

<table>
  <tr>
    <th>Ncbi taxon</th>
    <th>Type</th>
    <th>Value</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @taxon_attributes.each do |taxon_attribute| %>
  <tr>
    <td><%= taxon_attribute.ncbi_taxon_id %></td>
    <td><%= taxon_attribute.type %></td>
    <td><%= taxon_attribute.value %></td>
    <td><%= link_to 'Show', taxon_attribute %></td>
    <td><%= link_to 'Edit', edit_taxon_attribute_path(taxon_attribute) %></td>
    <td><%= link_to 'Destroy', taxon_attribute, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Taxon attribute', new_taxon_attribute_path %>

app/views/taxon_attributes/new.html.erb
<h1>New taxon_attribute</h1>

<%= render 'form' %>

<%= link_to 'Back', taxon_attributes_path %>

app/views/taxon_attributes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Ncbi taxon:</b>
  <%= @taxon_attribute.ncbi_taxon_id %>
</p>

<p>
  <b>Type:</b>
  <%= @taxon_attribute.type %>
</p>

<p>
  <b>Value:</b>
  <%= @taxon_attribute.value %>
</p>


<%= link_to 'Edit', edit_taxon_attribute_path(@taxon_attribute) %> |
<%= link_to 'Back', taxon_attributes_path %>