config/routes.rb
SllBiosql::Application.routes.draw do
  get "add_gis_to_queue" => "gi_queues#add_gis_to_queue"
  match "get_gis_sequences", to: "gi_queues#get_gis_sequences", via: [:get,:post]

  resources :functions
  get "functional_hierarchy" => "functions#functional_hierarchy"

  resources :organism_group_rows

  resources :organism_groups
  get "organism_group_by_name/:name" => "organism_groups#show_by_name"

  resources :taxon_attributes

  resources :protein_gi_taxons
  resources :fetch_gis
  
  resources :sequenced_genomes
  get "wgs_ncbi_taxon_ids" => "sequenced_genomes#all_ncbi_taxon_ids"
  get "gi2ncbi_taxon_id" => "protein_gi_taxons#gi2ncbi_taxon_id"
  get "gis2ncbi_taxon_ids" => "protein_gi_taxons#gis2ncbi_taxon_ids"
  resources :taxon_with_names

  root to: "static_pages#home"
  
  get "ncbi_taxon_id2full_taxon_hierarchy" => "taxon_with_names#ncbi_taxon_id2full_taxon_hierarchy"
  get "ncbi_taxon_ids2full_taxon_hierarchies" => "taxon_with_names#ncbi_taxon_ids2full_taxon_hierarchies"
  get "organism_group_name2full_taxon_hierarchies/:name" => "taxon_with_names#organism_group_name2full_taxon_hierarchies"

  get "gis2taxa" => "taxon_with_names#gis2taxa"

end

app/models/organism_group.rb
# == Schema Information
#
# Table name: organism_groups
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  test       :boolean
#  created_at :datetime        not null
#  updated_at :datetime        not null
#  source     :text
#

class OrganismGroup < ActiveRecord::Base
  attr_accessible :name, :test, :source
  validates :name, presence: true, uniqueness: true
  has_many :organism_group_rows, :dependent => :destroy
end

app/controllers/organism_groups_controller.rb
require 'file_parsers'
include FileParsers

class OrganismGroupsController < ApplicationController
  # GET /organism_groups
  # GET /organism_groups.json
  def index
    @organism_groups = OrganismGroup.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @organism_groups }
    end
  end

  # GET /organism_groups/1
  # GET /organism_groups/1.json
  def show
    @organism_group = OrganismGroup.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { _json }
    end
  end

  # GET /organism_group_by_name/?name=nnn
  def show_by_name
    @organism_group = OrganismGroup.find_by_name(params[:name])

    respond_to do |format|
      format.html { render :show }
      format.json { _json }
    end
  end

  # GET /organism_groups/new
  # GET /organism_groups/new.json
  def new
    @organism_group = OrganismGroup.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { _json }
    end
  end

  # GET /organism_groups/1/edit
  def edit
    @organism_group = OrganismGroup.find(params[:id])
  end

  # POST /organism_groups
  # POST /organism_groups.json
  def create
    @organism_group = OrganismGroup.new(params[:organism_group])

    respond_to do |format|
      if @organism_group.save
        format.html { redirect_to @organism_group, notice: 'Organism group was successfully created.' }
        format.json { render json: @organism_group, status: :created, location: @organism_group }
      else
        format.html { render action: "new" }
        format.json { render json: @organism_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /organism_groups/1
  # PUT /organism_groups/1.json
  def update
    @organism_group = OrganismGroup.find(params[:id])

    respond_to do |format|
      if @organism_group.update_attributes(params[:organism_group])
        format.html { redirect_to @organism_group, notice: 'Organism group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @organism_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organism_groups/1
  # DELETE /organism_groups/1.json
  def destroy
    @organism_group = OrganismGroup.find(params[:id])
    @organism_group.destroy

    respond_to do |format|
      format.html { redirect_to organism_groups_url }
      format.json { head :no_content }
    end
  end

private

  def _json
    #render json: { :name => @organism_group.name, :ncbi_taxon_ids => @organism_group.organism_group_rows.map { |ogr| ogr.ncbi_taxon_id } }
    #render json: { group: @organism_group, ncbi_taxon_ids: @organism_group.organism_group_rows.map { |ogr| ogr.ncbi_taxon_id } }
    render json: @organism_group.to_json(:include => :organism_group_rows)
  end
end

app/helpers/organism_groups_helper.rb
module OrganismGroupsHelper
end

app/views/organism_groups/_form.html.erb
<%= form_for(@organism_group) do |f| %>
  <% if @organism_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organism_group.errors.count, "error") %> prohibited this organism_group from being saved:</h2>

      <ul>
      <% @organism_group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :source %><br />
    <%= f.text_field :source %>
  </div>
  <div class="field">
    <%= f.label :test %><br />
    <%= f.check_box :test %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/organism_groups/edit.html.erb
<h1>Editing organism_group</h1>

<%= render 'form' %>

<%= link_to 'Show', @organism_group %> |
<%= link_to 'Back', organism_groups_path %>

app/views/organism_groups/index.html.erb
<h1>Listing organism_groups</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Source</th>
    <th>Test</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @organism_groups.each do |organism_group| %>
  <tr>
    <td><%= organism_group.name %></td>
    <td><%= organism_group.source %></td>
    <td><%= organism_group.test %></td>
    <td><%= link_to 'Show', organism_group %></td>
    <td><%= link_to 'Edit', edit_organism_group_path(organism_group) %></td>
    <td><%= link_to 'Destroy', organism_group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Organism group', new_organism_group_path %>

app/views/organism_groups/new.html.erb
<h1>New organism_group</h1>

<%= render 'form' %>

<%= link_to 'Back', organism_groups_path %>

app/views/organism_groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @organism_group.name %>
  <b>Source:</b>
  <%= @organism_group.source %>
  <b>Test:</b>
  <%= @organism_group.test %>
</p>

<table>
  <tr><th>NCBI taxon id</th><th>Source id</th></tr>
  <% @organism_group.organism_group_rows.each do |ogr| %>
    <tr>
      <td><%= ogr.ncbi_taxon_id %></td>
      <td><%= ogr.source_id %></td>
    </tr>
  <% end %>
</table>


<%= link_to 'Edit', edit_organism_group_path(@organism_group) %> |
<%= link_to 'Back', organism_groups_path %>